config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root 'pages#home'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }, skip: [:sessions, :registrations]
  match 'users/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup

  as :user do
    post '/login' => 'users/sessions#create', as: :user_session
    delete '/logout' => 'users/sessions#destroy', as: :destroy_user_session
  end

  get '/feed', to: 'ideas#index'

  resources :teams, param: :name do
    resources :memberships, except: [:show, :index], param: :username
  end

  scope ':username' do
    get '', to: 'profiles#show', as: :profile

    resources :ideas, except: [:index] do
      resources :comments
      resources :resources
      resource :description do
        resources :comments
      end

      post '/votes', to: 'votes#create', as: :vote
      delete '/votes', to: 'votes#destroy', as: :unvote
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
  belongs_to :user
end

app/models/description.rb
class Description < ActiveRecord::Base
  belongs_to  :idea
  has_many  :comments, as: :commentable
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  belongs_to :user
  belongs_to :team
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :voters, source: :user, through: :votes, dependent: :destroy
  has_many  :resources, dependent: :destroy
  has_one :description, dependent: :destroy

  after_create :create_description

  def is_deletable_by?(user)
    self.team.blank? && self.user == user || self.team.has_admin?(user)
  end
end

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user
  validates :uid, :provider, presence: true
  validates :uid, uniqueness: { scope: :provider }

  def self.find_for_oauth(auth)
    find_or_create_by(uid: auth.uid, provider: auth.provider)
  end
end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  belongs_to :team
  belongs_to :user
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  enum team_role: [:admin, :collaborator]

  belongs_to :user
  belongs_to :team

  after_create :set_admin

  private

  def set_admin
    memberships = self.team.memberships
    memberships.first.admin! if memberships.count == 1
  end
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  belongs_to :idea
  belongs_to :user
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships, after_add: :set_admin
  has_many :ideas

  validates :name, presence: true, uniqueness: true, format: { with: /\A[a-z0-9_-]+\z/ }

  def admin_users
    self.memberships.admin.map(&:user)
  end

  def remove_member(user)
    self.memberships.find_by(user: user).destroy
  end


  def has_admin?(user)
    self.admin_users.include?(user)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  TEMP_EMAIL_PREFIX = '@mesmerize.com'
  TEMP_EMAIL_REGEX = /\w@mesmerize.com\b/

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  has_one :identity, dependent: :destroy
  has_many :memberships, dependent: :destroy
  has_many :teams, through: :memberships
  has_many :ideas
  has_many :votes, dependent: :destroy
  has_many :voted_ideas, source: :idea, through: :votes, dependent: :destroy
  has_many :comments, as: :commentable
  has_many :resources, dependent: :destroy
  has_many :invitations, dependent: :destroy

  validates_format_of :email, without: TEMP_EMAIL_REGEX, on: :update

  def self.find_for_oauth(auth, signed_in_resource = nil)
    identity = Identity.find_for_oauth(auth)

    user = signed_in_resource || identity.user

    if user.blank?
      email = auth.info.email if auth.info.email && (auth.info.verified || auth.info.verified_email)

      if User.find_by(email: email).blank?
        user = User.new(
          name: auth.extra.raw_info.name,
          username: auth.info.nickname || auth.uid,
          image_url: auth.info.image,
          email: email ? email : "#{auth.info.nickname}-#{auth.provider}#{TEMP_EMAIL_PREFIX}",
          password: Devise.friendly_token[0,20]
        )
        # user.skip_confirmation!
        user.save!
      end
    end

    identity.update_attribute(:user, user) if identity.user != user

    user
  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end

  def image
    self.image_url.gsub('_normal', '')
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :idea

  validates_uniqueness_of :user_id, scope: :idea_id
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  layout 'application', only: [:new, :index]
  before_action :set_idea, except: [:index, :new, :create]
  skip_before_action :authenticate_user!, only: [:index, :show, :description]

  def index
    @ideas = (current_user.ideas.to_a + current_user.teams.map(&:ideas)).flatten.uniq
  end

  def show
    @comments = @idea.comments.order('id ASC')
  end

  def new
    @idea = current_user.ideas.new
    @teams = current_user.teams.collect {|team| [team.name, team.id]}
  end

  def create
    if current_user.ideas.create(idea_params)
      redirect_to profile_path(params[:username])
    else
      redirect_to new_idea_path, alert: 'Something went wrong. Please try again.'
    end
  end

  def edit
  end

  def update
    if @idea.update_attributes(idea_params)
      redirect_to profile_path(params[:username])
    else
      redirect_to edit_idea_path(username: params[:username], id: @idea.id), alert: 'Something went wrong. Please try again.'
    end
  end

  def destroy
    @idea.destroy if @idea.is_deletable_by?(current_user)
    redirect_to profile_path(params[:username])
  end

  def description
  end

  def edit_description
  end

  private

  def idea_params
    params.require(:idea).permit(:title, :brief, :description, :team_id)
  end

  def set_idea
    @idea = Idea.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!
  skip_before_action :ensure_signup_complete

  def home
    redirect_to feed_path if user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def activate(controller)
    controller == params[:controller] ? 'active' : ''
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/description_helper.rb
module DescriptionHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
  def activate_vote(idea)
    'voted' if idea.votes.count != 0 && idea.user != current_user
  end

  def set_action(idea)
    idea.voters.include?(current_user) ? 'DELETE' : 'POST'
  end
end

app/views/idea/new.html.slim
.container
  .row
    .col-md-6.col-md-offset-3
      = simple_form_for Idea.new, url: create_idea_path do |f|
        = f.input :title
        = f.input :description
        = f.button :submit, class: 'btn btn-primary'
      end

app/views/ideas/_sidebar.html.slim
.spacer-md-20
= link_to idea_path(id: @idea.id), class: "btn btn-idea-action btn-full-width #{activate('ideas')}" do
  span.fa.fa-asterisk.fa-text
  span Idea
= link_to idea_description_path(idea_id: @idea.id), class: "btn btn-idea-action btn-full-width #{activate('descriptions')}" do
  span.fa.fa-info-circle.fa-text
  span Description
= link_to '#', class: "btn btn-idea-action btn-full-width #{activate('builds')}" do
  span.fa.fa-gavel.fa-text
  span Builds
= link_to idea_resources_path(idea_id: @idea.id), class: "btn btn-idea-action btn-full-width #{activate('resources')}" do
  span.fa.fa-plus-square.fa-text
  span Resources

app/views/ideas/edit.html.slim
- content_for :banner_title, 'Edit Idea'
- content_for :edit do
  .pull-right = link_to idea_path(username: current_user.username, id: @idea.id), method: :delete, class: 'btn btn-brand-contrast' do
    span.fa.fa-trash.fa-sm.fa-white.fa-text
    span Delete
h4
  span.fa.fa-pencil-square-o.fa.fa-text.fa-lg.fa-brand
  | Refine until you're satisfied.

.spacer-md-40

= form_for @idea, url: { action: 'update' }, method: :patch do |f|
  .form-group
    = f.label :title, 'What do you want to call this idea?'
    = f.text_field :title, autofocus: true, class: 'form-control'
  .form-group
    = f.label :brief, 'Describe your idea in a nice and crisp statement'
    = f.text_area :brief, class: 'form-control'
  .spacer-md-20
  .clearfix
    .btn-group.pull-right
      = button_tag type: 'submit', class: 'btn btn-brand' do
        span.fa-text Edit
        .fa.fa-chevron-right.fa-xs

app/views/ideas/index.html.slim
- content_for :banner_title, 'Idea Feed'
section.pane-lg.profile-ideas
  .container = render partial: 'shared/ideas', locals: { ideas: @ideas, message: 'Jon Snow is dead.' }

app/views/ideas/new.html.slim
.container
  .row
    .col-md-6.col-md-offset-3
      .spacer-md-50
      .spacer-md-50
      .box.drop-box-shadow
        h4
          span.fa.fa-asterisk.fa.fa-brand.fa-text
          | Log your shots of awe moments!

        .spacer-md-40

        = form_for @idea, url: { action: 'create' }, html: { multipart: true } do |f|
          - if current_user.teams.present?
            .form-group
              = f.label :team_id, 'Where do you want to add this idea? (Leave blank for Profile Idea)'
              = f.select :team_id, @teams, {include_blank: :select}, class: 'form-control'
          .form-group
            = f.label :title, 'What do you want to call this idea?'
            = f.text_field :title, autofocus: true, class: 'form-control'
          .form-group
            = f.label :brief, 'Describe your idea in a nice and crisp statement'
            = f.text_area :brief, class: 'form-control'
          .spacer-md-20
          .clearfix
            .btn-group.pull-right
              = button_tag type: 'submit', class: 'btn btn-brand' do
                span.fa-text Next
                .fa.fa-chevron-right.fa-xs

app/views/ideas/show.html.slim
- content_for :banner_title, @idea.title
- content_for :edit do
  = link_to edit_idea_path(id: @idea.id) do
    span.fa.fa-pencil-square-o.fa-sm.fa-white edit
p = @idea.brief
.spacer-md-15
.comment-list
  = link_to '#comments' do
    span.fa.fa-comment-o.fa-text
    span = @comments.count
    |  Comments
  hr
  - @comments.each do |comment|
    .comment-box
      = image_tag comment.user.image_url, class: 'img-circle img-comments'
      h5 = link_to comment.user.username, profile_path(username: comment.user.username)
      p.h6 = comment.content
      hr
  .comment-form
    = form_for @idea.comments.new, url: idea_comments_path(idea_id: @idea), method: :post do |f|
      .form-group
        = f.label :content, 'Add a comment'
        = f.text_field :content, class: 'form-control'