config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root 'pages#home'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }, skip: [:sessions, :registrations]
  match 'users/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup

  as :user do
    post '/login' => 'users/sessions#create', as: :user_session
    delete '/logout' => 'users/sessions#destroy', as: :destroy_user_session
  end

  get '/feed', to: 'ideas#index'

  resources :teams, param: :name do
    resources :memberships, except: [:show, :index], param: :username
  end

  scope ':username' do
    get '', to: 'profiles#show', as: :profile

    resources :ideas, except: [:index] do
      resources :comments
      resources :resources
      resource :description do
        resources :comments
      end

      post '/votes', to: 'votes#create', as: :vote
      delete '/votes', to: 'votes#destroy', as: :unvote
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
  belongs_to :user
end

app/models/description.rb
class Description < ActiveRecord::Base
  belongs_to  :idea
  has_many  :comments, as: :commentable
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  belongs_to :user
  belongs_to :team
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :voters, source: :user, through: :votes, dependent: :destroy
  has_many  :resources, dependent: :destroy
  has_one :description, dependent: :destroy

  after_create :create_description

  def is_deletable_by?(user)
    self.team.blank? && self.user == user || self.team.has_admin?(user)
  end
end

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user
  validates :uid, :provider, presence: true
  validates :uid, uniqueness: { scope: :provider }

  def self.find_for_oauth(auth)
    find_or_create_by(uid: auth.uid, provider: auth.provider)
  end
end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  belongs_to :team
  belongs_to :user
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  enum team_role: [:admin, :collaborator]

  belongs_to :user
  belongs_to :team

  after_create :set_admin

  private

  def set_admin
    memberships = self.team.memberships
    memberships.first.admin! if memberships.count == 1
  end
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  belongs_to :idea
  belongs_to :user
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships, after_add: :set_admin
  has_many :ideas

  validates :name, presence: true, uniqueness: true, format: { with: /\A[a-z0-9_-]+\z/ }

  def admin_users
    self.memberships.admin.map(&:user)
  end

  def remove_member(user)
    self.memberships.find_by(user: user).destroy
  end


  def has_admin?(user)
    self.admin_users.include?(user)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  TEMP_EMAIL_PREFIX = '@mesmerize.com'
  TEMP_EMAIL_REGEX = /\w@mesmerize.com\b/

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  has_one :identity, dependent: :destroy
  has_many :memberships, dependent: :destroy
  has_many :teams, through: :memberships
  has_many :ideas
  has_many :votes, dependent: :destroy
  has_many :voted_ideas, source: :idea, through: :votes, dependent: :destroy
  has_many :comments, as: :commentable
  has_many :resources, dependent: :destroy
  has_many :invitations, dependent: :destroy

  validates_format_of :email, without: TEMP_EMAIL_REGEX, on: :update

  def self.find_for_oauth(auth, signed_in_resource = nil)
    identity = Identity.find_for_oauth(auth)

    user = signed_in_resource || identity.user

    if user.blank?
      email = auth.info.email if auth.info.email && (auth.info.verified || auth.info.verified_email)

      if User.find_by(email: email).blank?
        user = User.new(
          name: auth.extra.raw_info.name,
          username: auth.info.nickname || auth.uid,
          image_url: auth.info.image,
          email: email ? email : "#{auth.info.nickname}-#{auth.provider}#{TEMP_EMAIL_PREFIX}",
          password: Devise.friendly_token[0,20]
        )
        # user.skip_confirmation!
        user.save!
      end
    end

    identity.update_attribute(:user, user) if identity.user != user

    user
  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end

  def image
    self.image_url.gsub('_normal', '')
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :idea

  validates_uniqueness_of :user_id, scope: :idea_id
end

app/helpers/application_helper.rb
module ApplicationHelper
  def activate(controller)
    controller == params[:controller] ? 'active' : ''
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/description_helper.rb
module DescriptionHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
  def activate_vote(idea)
    'voted' if idea.votes.count != 0 && idea.user != current_user
  end

  def set_action(idea)
    idea.voters.include?(current_user) ? 'DELETE' : 'POST'
  end
end

app/views/layouts/_header.html.slim
section#header
  .container
    .row
      .col-xs-2
        .spacer-md-20
        = link_to 'Mesmerize', root_path, class: 'logo'
      .col-xs-10
        .cleafix
          .pull-right
            - if current_user.blank?
              .spacer-md-15
              = link_to user_omniauth_authorize_path(:twitter), class: 'btn btn-brand' do
                span.fa.fa-twitter.fa-text
                span Login via Twitter
            - else
              .spacer-md-10
              .dropdown
                button#profile-dropdown.btn.btn-transparent.dropdown-toggle data-toggle="dropdown" type="button"
                  = image_tag current_user.image_url, class: 'img-circle fa-text'
                  span.fa-text = current_user.name
                  span.caret
                ul.dropdown-menu aria-labelledby="profile-dropdown"
                  li = link_to 'Profile', profile_path(username: current_user.username)
                  li = link_to 'Idea Feed', feed_path
                  li = link_to 'Teams', teams_path
                  li = link_to 'Add Idea', new_idea_path(username: current_user.username)
                  li = link_to 'Logout', destroy_user_session_path, method: :delete

app/views/layouts/application.html.slim
- content_for :stylesheets do
  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true

- content_for :javascripts do
	= javascript_include_tag 'application'

= render template: 'layouts/base'

app/views/layouts/base.html.slim
doctype html
html
  head
    title
      | Mesmerize
      = " | #{yield(:title)}" if content_for?(:title)
    meta content="width=device-width, initial-scale=1.0" name="viewport"

    = yield :stylesheets
    = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Raleway:400,200,300,500,600,800', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Damion', media: 'all', 'data-turbolinks-track' => true
    = yield :meta
    = csrf_meta_tags
    /= favicon_link_tag 'favicon.ico'

  body
    - if content_for?(:custom_header)
      = yield :custom_header
    - else
      = render 'layouts/header'

    - if content_for? :content
      = yield :content
    - else
      - if content_for?(:banner_title)
        .spacer-md-10
        section#masthead-home.pane.pane-dark.square-texture
          .container
            .row
              .col-xs-12
                .clearfix
                  h3.title.pull-left = yield(:banner_title)
                  .pull-right
                    = yield(:edit) if content_for?(:edit)
      = yield

    = render 'layouts/footer'

    = yield :pre_javascripts
    = yield :javascripts
    = yield :post_javascripts

app/views/layouts/ideas.html.slim
- content_for :stylesheets do
  = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Oxygen:400,300,700', media: 'all', 'data-turbolinks-track' => true
  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true

- content_for :javascripts do
  = javascript_include_tag 'application'

- content_for :content do

  .spacer-md-10
  section#masthead-home.pane.pane-dark.square-texture
    .container
      .row
        .col-xs-3.col-no-gutter
        .col-xs-9.col-no-gutter
          .banner
            - if content_for(:banner_title)
              h3.title
                span.fa-text = yield(:banner_title)
                - if @idea.user == current_user || params[:controller] == 'resources'
                  = yield(:edit)

  .container
    .row.idea-single
      .col-xs-3.col-no-gutter
        = render partial: 'ideas/sidebar'
      .col-xs-9.col-no-gutter
        .box.drop-box-shadow
          = yield
    .spacer-md-50
    .spacer-md-50

= render template: 'layouts/base'

app/views/pages/home.html.slim
- content_for :custom_header do
  section.hidden


section#masthead-home.pane.pane-dark.square-texture.pane-no-padding
  .container
    .row
      .col-md-12
        = image_tag 'hand.png', class: 'img-hand'
        = image_tag 'bulb.png', class: 'img-bulb'
        h3.home-logo Mesmerize
        .spacer-md-30
        .text-center
          h1.home-title Don't let your ideas
          h1.home-title slip away again!
          p.h3.sub-text Mesmerize helps you log, polish & get them validated!
          .spacer-md-30
          = link_to user_omniauth_authorize_path(:twitter), class: 'btn btn-brand-contrast btn-home' do
            span.fa.fa-twitter.fa-text
            span Login via Twitter
          .spacer-md-50

.spacer-md-50
section#pitch.pane
  .container
    .row
      .col-xs-12
        .mesmerize-flow
          = image_tag 'flow.png', class: 'img-contained'

app/views/resources/index.html.slim
- content_for :banner_title, 'Resources'
- content_for :edit do
  .pull-right
    = link_to new_idea_resource_path(idea_id: @idea.id), class: 'btn btn-brand-contrast' do
      span.fa.fa-plus.fa-text
      span Add Resource

.spacer-md-15
ol.resource-list
  - if @resources.present?
    - @resources.each do |resource|
      li.resource-box
        p #{link_to resource.title, resource.slug} by #{link_to resource.user.username, profile_path(username: resource.user.username)}
        p = resource.description
        hr
  - else
    .spacer-md-20
    .text-center
      h3 Uh oh, no resources have been added to this idea.
      h3 Add one & help the poor chap out!
    .spacer-md-50

app/views/resources/new.html.slim
.container
  .row
    .col-md-6.col-md-offset-3
      .spacer-md-50
      .spacer-md-50
      .box.drop-box-shadow
        h4
          span.fa.fa-plus-square.fa-brand.fa-text
          | Add a Resource

        .spacer-md-40

        = form_for @idea.resources.new, url: idea_resources_path, method: :post do |f|
          .form-group
            = f.label :title, 'Give your resource a name'
            = f.text_field :title, autofocus: true, class: 'form-control', required: true
          .form-group
            = f.label :description, 'Add a description about the resource'
            = f.text_field :description, class: 'form-control'
          .form-group
            = f.label :slug, 'Add the resource URL'
            = f.text_field :slug, type: 'url', class: 'form-control', required: true
          .spacer-md-20
          .clearfix
            .btn-group.pull-right
              = button_tag type: 'submit', class: 'btn btn-brand' do
                .fa.fa-plus.fa-xs.fa-text
                span Add

app/views/shared/_ideas.html.slim
- if ideas.present?
  - ideas.each do |idea|
    .row
      .col-xs-1.col-no-gutter
        = link_to '#', class: "btn-vote #{activate_vote(idea)}", data: { username: idea.user.username, idea_id: idea.id, action: set_action(idea) } do
          .vote-icons.text-center
            p.fa.fa-chevron-up.fa-2x
            span.vote-num = idea.votes.count

      .col-xs-8.col-no-gutter
        .box.box-border-sides
          h3
            span.fa-text = idea.title
            - if idea.user == current_user
              = link_to edit_idea_path(username: idea.user.username, id: idea.id)
                span.fa.fa-pencil-square-o.fa-sm  edit
          p = idea.brief
          .comment-list
            span.fa.fa-comment-o.fa-text
            span = link_to "#{idea.comments.count} comments", idea_path(username: idea.user.username, id: idea.id)
      .col-xs-3.col-no-gutter
        = link_to idea_path(username: idea.user.username, id: idea.id), class: 'btn btn-idea-action btn-full-width' do
          span.fa.fa-asterisk.fa-text
          span Idea Page
        = link_to idea_description_path(username: idea.user.username, idea_id: idea.id), class: 'btn btn-idea-action btn-full-width' do
          span.fa.fa-info-circle.fa-text
          span Description
        = link_to '#', class: 'btn btn-idea-action btn-full-width' do
          span.fa.fa-gavel.fa-text
          span Builds
        = link_to idea_resources_path(username: idea.user.username, idea_id: idea.id), class: 'btn btn-idea-action btn-full-width' do
          span.fa.fa-plus-square.fa-text
          span Resources
    hr

- else
  .row
    .col-xs-12
      h3.text-center = message